"""Create a StarCitizenHelper v1.1 build with KeepRunning auto-stop.
Run beside StarCitizenHelperv1.0.py (or StarCitizenHelper.py).
The source file is never overwritten.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
candidates = [HERE / 'StarCitizenHelperv1.0.py', HERE / 'StarCitizenHelper.py']
src = next((p for p in candidates if p.exists()), None)
if src is None:
    raise SystemExit('Put this script beside StarCitizenHelperv1.0.py (or StarCitizenHelper.py), then run it again.')

dst = HERE / 'StarCitizenHelperv1.1.py'
if dst.exists():
    raise SystemExit(f'{dst.name} already exists. Rename or remove it before applying the upgrade again.')
text = src.read_text(encoding='utf-8')

def replace_once(old, new, label):
    global text
    if old not in text:
        raise RuntimeError(f'Could not locate the expected {label} code. Source was not changed.')
    text = text.replace(old, new, 1)

replace_once("s.title('StarCitizenHelperv1.0')", "s.title('StarCitizenHelperv1.1')", 'application title')
replace_once(
 "s.game_running=False;s.game_foreground=False;s.game_check=0;s.guard_last_log=0;s.keep=s.scan=s.hold=False;s.held=[];s.hold_pending=False;s.hold_token=0;s.last=time.monotonic();",
 "s.game_running=False;s.game_foreground=False;s.game_check=0;s.guard_last_log=0;s.keep=s.scan=s.hold=False;s.held=[];s.hold_pending=False;s.hold_token=0;s.injected_until=0;s.last=time.monotonic();",
 'startup state')
replace_once("keyboard.on_press(s.activity) # keyboard module does not have on_click", "keyboard.on_press(s.on_key_press) # keyboard module does not have on_click", 'keyboard activity hook')
replace_once(
 " def activity(s,*x):\n  if time.monotonic()>=s.ignore:s.last=time.monotonic()\n def send(s,source):s.ignore=time.monotonic()+.15;keyboard.press_and_release('tab');s.q.put(source+': sent Tab')",
 """ def activity(s,*x):
  if time.monotonic()>=s.ignore:s.last=time.monotonic()
 def on_key_press(s,event):
  # Delay a cancellation briefly so the KeepRunning toggle hotkey can turn it
  # off normally instead of being mistaken for an ordinary key press.
  s.activity()
  if event.event_type!=keyboard.KEY_DOWN or not s.hold or time.monotonic()<s.injected_until:return
  token=s.hold_token;name=event.name or 'unknown key'
  threading.Thread(target=s._cancel_hold_after_key,args=(name,token),daemon=True).start()
 def _cancel_hold_after_key(s,name,token):
  time.sleep(.08)
  if s.hold and token==s.hold_token and time.monotonic()>=s.injected_until:
   s.release();s.q.put('KeepRunning auto-disabled by key press: '+name)
 def tap(s,key):
  # Do not let the helper's own Tab or macro output stop KeepRunning.
  s.injected_until=time.monotonic()+.20;keyboard.press_and_release(key);s.injected_until=time.monotonic()+.20
 def send(s,source):s.ignore=time.monotonic()+.15;s.tap('tab');s.q.put(source+': sent Tab')""",
 'activity and Tab sender')
replace_once(
 "    if action:keyboard.press_and_release(action);time.sleep(float(m.get('delay',.1)))",
 "    if action:s.tap(action);time.sleep(float(m.get('delay',.1)))",
 'macro key sender')
replace_once(
 "  try:\n   for x in keys:keyboard.press(x)\n   s.held=keys;s.hold=True;s.hold_pending=False;s.q.put('KeepRunning toggled on: '+'+'.join(s.held))",
 "  try:\n   # Ignore only events generated by these programmatic key-downs.\n   s.injected_until=time.monotonic()+.20\n   for x in keys:keyboard.press(x)\n   s.held=keys;s.hold=True;s.hold_pending=False;s.injected_until=time.monotonic()+.20;s.q.put('KeepRunning toggled on: '+'+'.join(s.held))",
 'KeepRunning activation')

dst.write_text(text, encoding='utf-8')
print('Created', dst)
print('Original preserved:', src)
print('While KeepRunning is active, any physical key press automatically releases held keys.')
